name: Starplace
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  audioplayers: ^0.15.1
  material_design_icons_flutter: ^3.2.3895
  url_launcher: ^5.4.10
  google_fonts: ^1.1.0


dev_dependencies:

  flutter_test:
    sdk: flutter
    

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/background/
    - images/prequels/
    - images/classic/
    - images/sequels/
    - images/gifs/
    - assets/
    - assets/prequels/
    - assets/classic/
    - assets/sequels/
  fonts:
    - family: Starjedi
      fonts:
        - asset: fonts/Starjedi.ttf
    - family: Pacifico
      fonts:
      - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
      - asset: fonts/SourceSansPro-Regular.ttf
    - family : Nexa
      fonts:
      - asset: fonts/Nexa-Regular.ttf
      - asset: fonts/Nexa-Bold.ttf    
 